### ISSUE TITLE
Help in installing 

### ISSUE THREAD

**Issue by adgai19** [nvim-telescope/telescope-arecibo.nvim#3]
Hi, I tried to install telescope-arecibo.nvim and I am running into error. 
I followed the instructions on the main page and installed with arecibo with packer but I am running into this error.

```
E5108: Error executing lua .../telescope/_extensions/arecibo/websearch/http_client.lua:6: Could not find lua package "http.parser". Install it from luarocks with Packer.
```

when I ran ```lua print(pcall(require,'http.parser'))``` I got this error
```
false error loading module 'http.parser' from file '/usr/local/lib/lua/5.1/http/parser.so':
^I/usr/local/lib/lua/5.1/http/parser.so: undefined symbol: lua_getiuservalue
```
Can anyone help me in resolving this?

**Comment by pachacutec-dev** [comment]
same problem

**Comment by BenHerbst** [comment]
I also have the same problem

**Comment by adgai19** [comment]
From what I heard on TJ's stream, this plugin is broken currently.
